import os

PROJECT_PATH = os.environ.get('PROJECT_PATH')
UPLOAD_PATH = # A REMPLIR SELON STREAMLIT
CATBOOST_MODEL_PATH = # A REMPLIR
COUNTRYSIDE_MODEL_PATH = # A REMPLIR
CITY_MODEL_PATH = # A REMPLIR

'''Model params'''
LEARNING_RATE = 1.0
KERNEL_SHAPE = (3,3)
MIN_COUNT = 800
MAX_COUNT = 1400
BATCH_SIZE = 32
IMAGE_RESIZE = (132,306) #CHANGE ONLY FLOAT (BETWEEN 0 AND 1)
EPOCHS = 50
L2_REGULARIZER_VALUE = 0.01
